In [ ]:
import numpy as np

np.random.seed(1)
matches = 30

balls = np.random.randint(10, 61, size=matches)  # 10–60 balls
runs = []
sixes = []
fours = []

for b in balls:
    max_runs = b * 6
    r = np.random.randint(0, max_runs+1)  # runs limited by balls
    f = np.random.randint(0, min(r//4, b)+1)  # fours limited by runs & balls
    s = np.random.randint(0, min((r - f*4)//6 + 1, b-f)+1)  # sixes limited by remaining runs & balls
    runs.append(r)
    fours.append(f)
    sixes.append(s)

runs = np.array(runs)
fours = np.array(fours)
sixes = np.array(sixes)

player = np.column_stack((runs, balls, fours, sixes))
print(player)
print("\n Minimum runs player scored is :",np.min(runs))
print("\n Maximum runs player scored is :",np.max(runs))
print("\n Maximum balls faced by player is:",np.max(balls))
strike_rate=np.array((runs/balls)*100).round(2)

print("average strike rate of the player is :",(np.mean(strike_rate).round(2)))
boundry_runs=fours*4+sixes*6
with np.errstate(divide='ignore', invalid='ignore'):
    boundry_percentage = np.where(runs > 0, (boundry_runs/runs)*100, 0)

print("\nBoundry percentage of matches are :",boundry_percentage.round(2),"%")

#scoring miles stone
fifties=np.sum(runs>=50)
hundereds=np.sum(runs>=100)
print("\nNumber of 50+ runs scored by player is :",fifties)
print("\nNumber of 100+ runs scored by player is:",hundereds)
highest_runs=np.argmax(runs)
print("\nplayer scored highest runs in match no:",highest_runs+1)
highest_run_strike=(runs[highest_runs]/balls[highest_runs])*100
print("\nThe Strike rate of match no:",highest_runs+1,"is", highest_run_strike)
lowest_runs=np.argmin(runs)
print("\nplayer scored lowest runs in match no:",lowest_runs+1)
lowest_run_strike=(runs[lowest_runs]/balls[lowest_runs])*100
print("\nThe Strike rate of match no:",lowest_runs+1,"is", lowest_run_strike)

#consistency
print("\n The average runs player scored is :",np.mean(runs).round(2))
more_avg=np.sum(runs>np.mean(runs))
print("\n Number of matches in which player scored more than his average is :",more_avg)

#Boundary Analysis
avg_boundary_percentage=np.mean(boundry_percentage.round(2))
print("\nThe average boundary percentage is :",avg_boundary_percentage,"%")
if avg_boundary_percentage>60:
    print("\nPlayer is aggressive Batsman")
else:
    print("\nPlayer is stable Batsman")


#non boundary analysis
# non_boundary_runs=runs-boundry_runs
# print(non_boundary_runs)
# if np.all(non_boundary_runs>boundry_runs):
#     print("\n Player mostly rely on singles and doubles")
# else:
#     print("\nPlayer mostly rely on hitting boundaries")

# non boundary analysis
non_boundary=runs-boundry_runs
singles_doubles=np.sum(non_boundary>boundry_runs)
if singles_doubles>matches//2:
    print("\n Player mostly rely on singles and doubles")
else:
    print("\nPlayer mostly rely on hitting boundaries\n")    


#series analysis
series_avg=[]
for i in range(0,matches,5):
    avg_series=np.mean(runs[i:i+5])
    series_avg.append(avg_series)
    print(f"averages runs of Series {i+1}-{i+5} is {avg_series} runs")
highest_avg_series=np.argmax(series_avg)
print("Highest averages of the series is :",highest_avg_series+1)

#correlation check
corr_matrix=np.corrcoef(runs,balls)
corr_value=corr_matrix[0,1]
print("\n Correlation between runs and balls :",corr_value.round(2))
if corr_value > 0.7:
    print("→ Strong positive relation: More balls faced → More runs scored.")
elif corr_value > 0.3:
    print("→ Moderate positive relation: Runs thoda balls pe depend karte hain.")
elif corr_value > 0:
    print("→ Weak positive relation: Runs ka balls se zyada relation nahi hai.")
elif corr_value == 0:
    print("→ No relation: Runs aur balls independent hain.")
else:
    print("→ Negative relation: More balls faced but fewer runs scored (rare case).")

#consistency check by standard deviation
std_runs=np.std(runs).round(2)
print("\n Standard Deviation of the runs is :",std_runs)
#ducks highlight
ducks = np.sum(runs == 0)
print("\nNumber of Ducks (0 runs):", ducks)
#match highlight
print(f"\nHighlight: On Match {highest_runs+1}, Player scored {runs[highest_runs]} \
runs in {balls[highest_runs]} balls with strike rate {(runs[highest_runs]/balls[highest_runs]*100).round(2)} \
hitting {fours[highest_runs]} fours and {sixes[highest_runs]} sixes.")


#final data set 
final_data = np.column_stack((runs, balls, fours, sixes, strike_rate.round(2)))
print("\nFinal Dataset:\n",final_data.round(2))

[[241  47  30   0]
 [ 86  53  13   1]
 [  7  22   1   1]
 [ 22  18   1   1]
 [  0  19   0   0]
 [ 81  21   8   8]
 [ 13  15   3   1]
 [121  25   8  14]
 [  7  10   1   0]
 [149  26  17   9]
 [  3  11   0   0]
 [ 24  22   1   3]
 [ 76  17  16   1]
 [297  55  18  15]
 [ 64  16   4   9]
 [111  35   2   7]
 [282  60  25   8]
 [ 22  30   1   3]
 [126  47  23   5]
 [100  28   5   9]
 [ 83  30   6   8]
 [ 32  21   2   2]
 [279  52  15  23]
 [ 25  38   3   0]
 [ 74  39  14   0]
 [ 65  24  13   3]
 [253  60  13   6]
 [ 52  14   5   6]
 [  2  33   0   0]
 [149  33  11   7]]

 Minimum runs player scored is : 0

 Maximum runs player scored is : 297

 Maximum balls faced by player is: 60
average strike rate of the player is : 272.68

Boundry percentage of matches are : [ 49.79  67.44 142.86  45.45   0.    98.77 138.46  95.87  57.14  81.88
   0.    91.67  92.11  54.55 109.38  45.05  52.48 100.    96.83  74.
  86.75  62.5   70.97  48.    75.68 107.69  34.78 107.69   0.    57.72] %

Number of 50+ runs